name: djibly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.25+6

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^10.3.0
  http: ^0.13.3
  shared_preferences: ^2.0.11
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  provider: ^6.0.5
  fluttertoast: ^8.1.2
  url_launcher: ^6.0.3
  expandable: ^4.1.4
  pin_input_text_field: ^3.1.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.1.1
  uuid: 3.0.7
  geolocator: ^7.0.3
  skeleton_text: ^1.0.0
  awesome_select: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  rflutter_alert: ^1.1.0
  flutter_rating_bar: ^3.2.0+1
  flutter_overlay_loader: ^0.0.2
  device_apps: ^2.1.1
  image_picker: ^0.8.4
  image_cropper: ^1.4.1
  timeline_tile: ^2.0.0
  otp_autofill: ^3.0.1
  otp_text_field: ^1.1.3
  intl: ^0.17.0
  dio: ^5.3.3
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.2.0
  flutter_localization: ^0.1.14
  restart_app: ^1.1.2
  feather_icons: ^1.2.0
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  get: ^4.6.5
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/markers/
    - assets/images/categories/
    - assets/images/payments/
    - assets/images/home/
    - assets/images/ads/
    - assets/images/delivery/
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"

  image: assets/images/logo_djibly.png
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
