// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqg2ksk0SFsbDPI5se0AwGRU1GtU889Ps',
    appId: '1:102490073065:web:0c16ba77e8f804c3894d78',
    messagingSenderId: '102490073065',
    projectId: 'djibly-946e6',
    authDomain: 'djibly-946e6.firebaseapp.com',
    storageBucket: 'djibly-946e6.appspot.com',
    measurementId: 'G-SB9KQC3M13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqg2ksk0SFsbDPI5se0AwGRU1GtU889Ps',
    appId: '1:102490073065:android:b3230dceff87f674894d78',
    messagingSenderId: '102490073065',
    projectId: 'djibly-946e6',
    storageBucket: 'djibly-946e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvw2YdFCJH4G67u-3Ku5qrIh6sQwXmqE',
    appId: '1:102490073065:ios:c06084464dbcec41894d78',
    messagingSenderId: '102490073065',
    projectId: 'djibly-946e6',
    storageBucket: 'djibly-946e6.appspot.com',
    iosBundleId: 'dz.djezzy.djibly',
  );
}
